data:
  root_dir: ./dataset/
  n_hr_views: 2
  n_lr_views: 0
  crop_sizes: 
    - [208, 576]
    - [208, 576]
  min_scales: [1.0, 0.2]
  max_scales: [1.0, 0.5] 
training:
  device: 'cuda'
  backbone_model: 'resnet18'  
  n_features_swav: 128
  batch_size: 128
  n_prototypes: 300
  learning_rate: 0.0001
  sinkhorn_epsilon: 0.03
  max_patience: 3
  min_epochs: 10
  checkpoints_file_path: ./checkpoints/
  weights_file_name: null
